# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\retractor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(799, 939)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(120, 60, 541, 701))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ateHeading = QtWidgets.QLabel(self.frame)
        self.ateHeading.setGeometry(QtCore.QRect(70, 115, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.ateHeading.setFont(font)
        self.ateHeading.setStyleSheet("border:4px solid black;background-color: rgb(250, 249, 246);")
        self.ateHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.ateHeading.setObjectName("ateHeading")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(29, 173, 491, 521))
        self.label_5.setStyleSheet("border:4px solid black;border-radius:30px;background-color: rgb(250, 249, 246);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(50, 230, 451, 251))
        self.textBrowser.setObjectName("textBrowser")
        self.serialLabel = QtWidgets.QLabel(self.frame)
        self.serialLabel.setGeometry(QtCore.QRect(60, 510, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.serialLabel.setFont(font)
        self.serialLabel.setObjectName("serialLabel")
        self.lineEditBarcode = QtWidgets.QLineEdit(self.frame)
        self.lineEditBarcode.setGeometry(QtCore.QRect(210, 510, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditBarcode.setFont(font)
        self.lineEditBarcode.setStyleSheet("QLineEdit{\n"
"background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 3px solid rgba(42,226,230,255);\n"
"color:rgba(0,0,0,255);\n"
"padding-bottom:7px;\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.323864 rgba(222, 45, 175, 255), stop:0.5 rgba(211, 61, 235, 255), stop:0.642045 rgba(157, 45, 241, 255), stop:1 rgba(0, 0, 255, 255));\n"
"}\n"
"")
        self.lineEditBarcode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditBarcode.setObjectName("lineEditBarcode")
        self.lineEditName = QtWidgets.QLineEdit(self.frame)
        self.lineEditName.setGeometry(QtCore.QRect(209, 550, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditName.setFont(font)
        self.lineEditName.setToolTipDuration(0)
        self.lineEditName.setStyleSheet("QLineEdit{\n"
"background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:3px solid rgba(42,226,230,255);\n"
"color:rgba(0,0,0,255);\n"
"padding-bottom:7px;\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.323864 rgba(222, 45, 175, 255), stop:0.5 rgba(211, 61, 235, 255), stop:0.642045 rgba(157, 45, 241, 255), stop:1 rgba(0, 0, 255, 255));\n"
"}\n"
"")
        self.lineEditName.setInputMask("")
        self.lineEditName.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditName.setClearButtonEnabled(False)
        self.lineEditName.setObjectName("lineEditName")
        self.nameLabel = QtWidgets.QLabel(self.frame)
        self.nameLabel.setGeometry(QtCore.QRect(60, 560, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.start = QtWidgets.QPushButton(self.frame)
        self.start.setGeometry(QtCore.QRect(60, 610, 201, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.start.setFont(font)
        self.start.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.323864 rgba(222, 45, 175, 255), stop:0.5 rgba(211, 61, 235, 255), stop:0.642045 rgba(157, 45, 241, 255), stop:1 rgba(0, 0, 255, 255));\n"
"font: 75 20pt \'MS Shell Dlg 2\';\n"
"border-top-left-radius:30px;\n"
"border-bottom-right-radius:30px;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton::hover{\n"
"font: 75 25pt \'MS Shell Dlg 2\';\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.323864 rgba(222, 45, 175, 255), stop:0.5 rgba(211, 61, 235, 255), stop:0.642045 rgba(157, 45, 241, 255), stop:1 rgba(0, 0, 255, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton::pressed{\n"
"font: 75 25pt \'MS Shell Dlg 2\';\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.323864 rgba(222, 45, 175, 255), stop:0.5 rgba(211, 61, 235, 255), stop:0.642045 rgba(157, 45, 241, 255), stop:1 rgba(0, 0, 255, 255));\n"
"padding-top:10px;\n"
"}\n"
"")
        self.start.setObjectName("start")
        self.log = QtWidgets.QPushButton(self.frame)
        self.log.setGeometry(QtCore.QRect(290, 610, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.log.setFont(font)
        self.log.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.323864 rgba(222, 45, 175, 255), stop:0.5 rgba(211, 61, 235, 255), stop:0.642045 rgba(157, 45, 241, 255), stop:1 rgba(0, 0, 255, 255));\n"
"font: 75 20pt \'MS Shell Dlg 2\';\n"
"border-top-right-radius:30px;\n"
"border-bottom-left-radius:30px;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton::hover{\n"
"font: 75 25pt \'MS Shell Dlg 2\';\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.323864 rgba(222, 45, 175, 255), stop:0.5 rgba(211, 61, 235, 255), stop:0.642045 rgba(157, 45, 241, 255), stop:1 rgba(0, 0, 255, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton::pressed{\n"
"font: 75 25pt \'MS Shell Dlg 2\';\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.323864 rgba(222, 45, 175, 255), stop:0.5 rgba(211, 61, 235, 255), stop:0.642045 rgba(157, 45, 241, 255), stop:1 rgba(0, 0, 255, 255));\n"
"padding-top:10px;\n"
"}\n"
"")
        self.log.setObjectName("log")
        self.light = QtWidgets.QLabel(self.frame)
        self.light.setGeometry(QtCore.QRect(50, 40, 440, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.light.setFont(font)
        self.light.setStyleSheet("QLabel{\n"
"border:4px solid black;\n"
"border-radius:30px;\n"
"color:black;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.323864 rgba(222, 45, 175, 255), stop:0.5 rgba(211, 61, 235, 255), stop:0.642045 rgba(157, 45, 241, 255), stop:1 rgba(0, 0, 255, 255));\n"
"}")
        self.light.setText("")
        self.light.setScaledContents(True)
        self.light.setAlignment(QtCore.Qt.AlignCenter)
        self.light.setObjectName("light")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 481, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"border:4px solid black;\n"
"border-radius:40px;\n"
"    \n"
"    background-color: rgb(250, 249, 246);\n"
"}")
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.exitButton = QtWidgets.QPushButton(self.frame)
        self.exitButton.setGeometry(QtCore.QRect(499, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad, x1:0.142045, y1:0.148, x2:1, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.704545 rgba(144, 0, 0, 255));border-radius:10px;}\n"
"\n"
"\n"
"QPushButton::hover{background-color: qlineargradient(spread:pad, x1:0.142045, y1:0.148, x2:1, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.704545 rgba(144, 0, 0, 255));border:rgba(170,0,250,255);border-radius:5px;}\n"
"\n"
"\n"
"QPushButton::pressed{padding-top:10px;padding-up:5px;background-color: qlineargradient(spread:pad, x1:0.142045, y1:0.148, x2:1, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.704545 rgba(144, 0, 0, 255));}")
        self.exitButton.setObjectName("exitButton")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(380, 190, 121, 36))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom: 3px solid rgba(42,226,230,255);\n"
"color:rgba(0,0,0,255);\n"
"padding-bottom:7px;\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.323864 rgba(222, 45, 175, 255), stop:0.5 rgba(211, 61, 235, 255), stop:0.642045 rgba(157, 45, 241, 255), stop:1 rgba(0, 0, 255, 255));\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"}")
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(280, 189, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2.raise_()
        self.label_5.raise_()
        self.ateHeading.raise_()
        self.textBrowser.raise_()
        self.serialLabel.raise_()
        self.lineEditBarcode.raise_()
        self.lineEditName.raise_()
        self.nameLabel.raise_()
        self.start.raise_()
        self.log.raise_()
        self.light.raise_()
        self.exitButton.raise_()
        self.comboBox.raise_()
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ateHeading.setText(_translate("Form", "Retractor LED Testing"))
        self.serialLabel.setText(_translate("Form", "Serial Number"))
        self.lineEditBarcode.setPlaceholderText(_translate("Form", "Enter Barcode here"))
        self.lineEditName.setPlaceholderText(_translate("Form", "Enter your name"))
        self.nameLabel.setText(_translate("Form", "Associate Name"))
        self.start.setText(_translate("Form", "Start Test"))
        self.log.setText(_translate("Form", "Logs"))
        self.exitButton.setToolTip(_translate("Form", "CLOSE"))
        self.exitButton.setText(_translate("Form", "X"))
        self.comboBox.setCurrentText(_translate("Form", "New Item"))
        self.comboBox.setItemText(0, _translate("Form", "New Item"))
        self.comboBox.setItemText(1, _translate("Form", "New Item"))
        self.label.setText(_translate("Form", "COM Port:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
